export declare const getCssVariable: (variable: string) => string;
export declare const querySelectorAll: (selector: string) => NodeListOf<Element>;
export declare const querySelector: (selector: string) => Element | null;
export declare const queryChildSelector: (selector: string, parent: HTMLElement) => Element | null;
export declare const getElementById: (id: string) => HTMLElement | null;
export declare const removeCssProperty: import("lodash").CurriedFunction2<keyof CSSStyleDeclaration | (keyof CSSStyleDeclaration)[], HTMLElement | HTMLElement[], HTMLElement | HTMLElement[]>;
export declare const addCssProperty: import("lodash").CurriedFunction2<[keyof CSSStyleDeclaration, string | number], HTMLElement, HTMLElement>;
export declare const getRect: (element: HTMLElement) => Omit<DOMRect, 'toJSON'>;
export declare const getRectField: import("lodash").CurriedFunction2<"height" | "width" | "bottom" | "left" | "right" | "top" | "x" | "y", HTMLElement, number>;
export declare const arrayOfElements: (selector: string) => unknown[];
export declare const collectSrcSet: (src: string[]) => string;
export declare const setHref: import("lodash").CurriedFunction2<string, HTMLLinkElement | HTMLAnchorElement, HTMLLinkElement | HTMLAnchorElement>;
export declare const setFavicon: (iconLink: string) => void;
