import dayjs from 'dayjs';
import now from 'lodash/now';
export { now as dateNow, };
export type DateValue = Date | number | string;
export declare const isDateBefore: import("lodash").CurriedFunction2<DateValue, DateValue, boolean>;
export declare const toISOString: (date: DateValue) => string;
export declare const humanizeDate: (date: DateValue) => string;
export declare const customFormatDate: import("lodash").CurriedFunction2<string, DateValue, string>;
export declare const secondsToMilliseconds: (seconds: number) => number;
export declare const millisecondsToSeconds: (milliseconds: number) => number;
export declare const addMilliseconds: import("lodash").CurriedFunction2<number, DateValue, dayjs.Dayjs>;
export declare const addSeconds: import("lodash").CurriedFunction2<number, DateValue, dayjs.Dayjs>;
export declare const subtractSeconds: import("lodash").CurriedFunction2<number, DateValue, dayjs.Dayjs>;
export declare const addMinutes: import("lodash").CurriedFunction2<number, DateValue, dayjs.Dayjs>;
export declare const subtractMinutes: import("lodash").CurriedFunction2<number, DateValue, dayjs.Dayjs>;
export declare const addHours: import("lodash").CurriedFunction2<number, DateValue, dayjs.Dayjs>;
export declare const addDays: import("lodash").CurriedFunction2<number, DateValue, dayjs.Dayjs>;
export declare const subtractDays: import("lodash").CurriedFunction2<number, DateValue, dayjs.Dayjs>;
export declare const addMonths: import("lodash").CurriedFunction2<number, DateValue, dayjs.Dayjs>;
export declare const subtractMonths: import("lodash").CurriedFunction2<number, DateValue, dayjs.Dayjs>;
export declare const subtractYears: import("lodash").CurriedFunction2<number, DateValue, dayjs.Dayjs>;
export declare const toTimestamp: (date: DateValue) => number;
export declare const toSecondsTimestamp: (date: DateValue) => number;
export declare const isDateWithinCurrentMonth: (date: DateValue) => boolean;
export declare const isDateWithinCurrentDay: (date: DateValue) => boolean;
export declare const isDateWithinCurrentWeek: (date: DateValue) => boolean;
export declare const getMonthIndex: (date: DateValue) => number;
export declare const getMonthName: (monthIndex: number) => string;
export declare const getDateDifferenceIn: import("lodash").CurriedFunction3<dayjs.QUnitType, DateValue, DateValue, number>;
export declare const getDifferenceInMonths: import("lodash").CurriedFunction2<DateValue, DateValue, number>;
