const o = "_wrapper_1skfl_30", e = "_disabled_1skfl_34", s = "_label_1skfl_39", t = "_options_1skfl_42", l = "_vertical_1skfl_51", a = "_item_1skfl_55", _ = "_ghost_1skfl_66", r = "_animated_1skfl_71", n = "_primaryColor_1skfl_75", i = "_primaryColor2_1skfl_75", c = "_active_1skfl_83", k = "_defaultSize_1skfl_99", f = "_mdSize_1skfl_116", d = "_lgSize_1skfl_133", p = "_secondaryColor5_1skfl_149", m = "_secondaryColor2_1skfl_164", C = "_blueGlassVerticalRight_1skfl_177", g = "_specialFavoritesSize_1skfl_188", v = "_simpleColor_1skfl_195", T = "_tabsShape_1skfl_205", u = "_successBackground_1skfl_223", y = "_dangerBackground_1skfl_227", S = "_primaryTextColor_1skfl_231", b = "_danger2TextColor_1skfl_235", z = "_accent1TextColor_1skfl_239", h = {
  "fade-animation": "_fade-animation_1skfl_11",
  "skeletonTransition-enter-active": "_skeletonTransition-enter-active_1skfl_15",
  "skeletonTransition-leave-active": "_skeletonTransition-leave-active_1skfl_15",
  "skeletonTransition-enter-from": "_skeletonTransition-enter-from_1skfl_18",
  "skeletonTransition-leave-to": "_skeletonTransition-leave-to_1skfl_18",
  wrapper: o,
  disabled: e,
  label: s,
  options: t,
  vertical: l,
  item: a,
  ghost: _,
  animated: r,
  "options-ghost": "_options-ghost_1skfl_1",
  primaryColor: n,
  primaryColor2: i,
  active: c,
  defaultSize: k,
  mdSize: f,
  lgSize: d,
  secondaryColor5: p,
  secondaryColor2: m,
  blueGlassVerticalRight: C,
  specialFavoritesSize: g,
  simpleColor: v,
  tabsShape: T,
  successBackground: u,
  dangerBackground: y,
  primaryTextColor: S,
  danger2TextColor: b,
  accent1TextColor: z
};
export {
  z as accent1TextColor,
  c as active,
  r as animated,
  C as blueGlassVerticalRight,
  b as danger2TextColor,
  y as dangerBackground,
  h as default,
  k as defaultSize,
  e as disabled,
  _ as ghost,
  a as item,
  s as label,
  d as lgSize,
  f as mdSize,
  t as options,
  n as primaryColor,
  i as primaryColor2,
  S as primaryTextColor,
  m as secondaryColor2,
  p as secondaryColor5,
  v as simpleColor,
  g as specialFavoritesSize,
  u as successBackground,
  T as tabsShape,
  l as vertical,
  o as wrapper
};
//# sourceMappingURL=Selector.vue3.js.map
