const o = "_button_e1old_22", e = "_disabled_e1old_30", n = "_wide_e1old_41", r = "_hideLoaderOnHover_e1old_45", d = "_loaderCap_e1old_45", t = "_inner_e1old_49", _ = "_hidden_e1old_62", l = "_interactive_e1old_75", c = "_textAccent1_e1old_82", a = "_textAccent2_e1old_86", s = "_primaryColor_e1old_93", i = "_gradientColor_e1old_98", C = "_blueGradientColor_e1old_103", g = "_orangeGradientColor_e1old_108", u = "_successColor_e1old_113", b = "_dangerColor_e1old_118", k = "_colored_e1old_123", v = "_secondary1Color_e1old_128", m = "_secondary2Color_e1old_133", y = "_background1_e1old_141", p = "_background2_e1old_149", x = "_greyBordered_e1old_157", A = "_background3_e1old_162", f = "_backgroundAccent1_e1old_170", T = "_accent3Color_e1old_174", h = "_borderedDefault_e1old_182", w = "_nowrap_e1old_190", G = "_xl_e1old_194", B = "_lg_e1old_202", D = "_md_e1old_210", H = "_sm_e1old_219", L = {
  "fade-animation": "_fade-animation_e1old_11",
  "skeletonTransition-enter-active": "_skeletonTransition-enter-active_e1old_15",
  "skeletonTransition-leave-active": "_skeletonTransition-leave-active_e1old_15",
  "skeletonTransition-enter-from": "_skeletonTransition-enter-from_e1old_18",
  "skeletonTransition-leave-to": "_skeletonTransition-leave-to_e1old_18",
  button: o,
  disabled: e,
  wide: n,
  hideLoaderOnHover: r,
  loaderCap: d,
  inner: t,
  hidden: _,
  interactive: l,
  textAccent1: c,
  textAccent2: a,
  primaryColor: s,
  gradientColor: i,
  blueGradientColor: C,
  orangeGradientColor: g,
  successColor: u,
  dangerColor: b,
  colored: k,
  secondary1Color: v,
  secondary2Color: m,
  background1: y,
  background2: p,
  greyBordered: x,
  background3: A,
  backgroundAccent1: f,
  accent3Color: T,
  borderedDefault: h,
  nowrap: w,
  xl: G,
  lg: B,
  md: D,
  sm: H
};
export {
  T as accent3Color,
  y as background1,
  p as background2,
  A as background3,
  f as backgroundAccent1,
  C as blueGradientColor,
  h as borderedDefault,
  o as button,
  k as colored,
  b as dangerColor,
  L as default,
  e as disabled,
  i as gradientColor,
  x as greyBordered,
  _ as hidden,
  r as hideLoaderOnHover,
  t as inner,
  l as interactive,
  B as lg,
  d as loaderCap,
  D as md,
  w as nowrap,
  g as orangeGradientColor,
  s as primaryColor,
  v as secondary1Color,
  m as secondary2Color,
  H as sm,
  u as successColor,
  c as textAccent1,
  a as textAccent2,
  n as wide,
  G as xl
};
//# sourceMappingURL=Button.vue3.js.map
