const e = "_table_m0b2l_22", o = "_head_m0b2l_28", l = "_records_m0b2l_33", t = "_rowsClickable_m0b2l_37", n = "_record_m0b2l_33", _ = "_column_m0b2l_43", r = "_clickable_m0b2l_43", a = "_recordColumn_m0b2l_47", c = "_center_m0b2l_51", s = "_left_m0b2l_54", i = "_right_m0b2l_57", b = "_tableContent_m0b2l_61", m = "_placeholder_m0b2l_67", d = "_tableRow_m0b2l_77", C = "_tableRowContainer_m0b2l_81", k = "_row_m0b2l_37", w = "_scrollable_m0b2l_93", f = "_defaultSize_m0b2l_120", u = "_smSize_m0b2l_141", h = "_tinySize_m0b2l_156", z = "_secondaryColor3_m0b2l_184", S = "_orderListColor_m0b2l_191", v = {
  "fade-animation": "_fade-animation_m0b2l_11",
  "skeletonTransition-enter-active": "_skeletonTransition-enter-active_m0b2l_15",
  "skeletonTransition-leave-active": "_skeletonTransition-leave-active_m0b2l_15",
  "skeletonTransition-enter-from": "_skeletonTransition-enter-from_m0b2l_18",
  "skeletonTransition-leave-to": "_skeletonTransition-leave-to_m0b2l_18",
  table: e,
  head: o,
  records: l,
  rowsClickable: t,
  record: n,
  column: _,
  clickable: r,
  recordColumn: a,
  center: c,
  left: s,
  right: i,
  tableContent: b,
  placeholder: m,
  tableRow: d,
  tableRowContainer: C,
  row: k,
  scrollable: w,
  defaultSize: f,
  smSize: u,
  tinySize: h,
  secondaryColor3: z,
  orderListColor: S
};
export {
  c as center,
  r as clickable,
  _ as column,
  v as default,
  f as defaultSize,
  o as head,
  s as left,
  S as orderListColor,
  m as placeholder,
  n as record,
  a as recordColumn,
  l as records,
  i as right,
  k as row,
  t as rowsClickable,
  w as scrollable,
  z as secondaryColor3,
  u as smSize,
  e as table,
  b as tableContent,
  d as tableRow,
  C as tableRowContainer,
  h as tinySize
};
//# sourceMappingURL=Table.vue2.js.map
